# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1043, 582)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab_widget = QtGui.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 1051, 511))
        self.tab_widget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab_canvas = QtGui.QWidget()
        self.tab_canvas.setObjectName(_fromUtf8("tab_canvas"))
        self.label_2 = QtGui.QLabel(self.tab_canvas)
        self.label_2.setGeometry(QtCore.QRect(260, 420, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_count = QtGui.QLabel(self.tab_canvas)
        self.label_count.setGeometry(QtCore.QRect(450, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_count.setFont(font)
        self.label_count.setText(_fromUtf8(""))
        self.label_count.setObjectName(_fromUtf8("label_count"))
        self.label_score = QtGui.QLabel(self.tab_canvas)
        self.label_score.setGeometry(QtCore.QRect(310, 370, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_score.setFont(font)
        self.label_score.setText(_fromUtf8(""))
        self.label_score.setObjectName(_fromUtf8("label_score"))
        self.widget_canvas = QtGui.QWidget(self.tab_canvas)
        self.widget_canvas.setEnabled(False)
        self.widget_canvas.setGeometry(QtCore.QRect(20, 20, 911, 371))
        self.widget_canvas.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.widget_canvas.setObjectName(_fromUtf8("widget_canvas"))
        self.label = QtGui.QLabel(self.tab_canvas)
        self.label.setGeometry(QtCore.QRect(810, 420, 111, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.combo_box = QtGui.QComboBox(self.tab_canvas)
        self.combo_box.setGeometry(QtCore.QRect(150, 420, 74, 22))
        self.combo_box.setObjectName(_fromUtf8("combo_box"))
        self.combo_box.addItem(_fromUtf8(""))
        self.combo_box.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.tab_canvas)
        self.label_3.setGeometry(QtCore.QRect(80, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton_NN = QtGui.QRadioButton(self.tab_canvas)
        self.radioButton_NN.setGeometry(QtCore.QRect(40, 460, 41, 17))
        self.radioButton_NN.setObjectName(_fromUtf8("radioButton_NN"))
        self.radioButton_pd = QtGui.QRadioButton(self.tab_canvas)
        self.radioButton_pd.setGeometry(QtCore.QRect(100, 460, 41, 17))
        self.radioButton_pd.setChecked(True)
        self.radioButton_pd.setObjectName(_fromUtf8("radioButton_pd"))
        self.tab_widget.addTab(self.tab_canvas, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.button_restore_def = QtGui.QPushButton(self.tab_2)
        self.button_restore_def.setGeometry(QtCore.QRect(817, 440, 111, 23))
        self.button_restore_def.setObjectName(_fromUtf8("button_restore_def"))
        self.button_save_conf = QtGui.QPushButton(self.tab_2)
        self.button_save_conf.setGeometry(QtCore.QRect(670, 440, 111, 23))
        self.button_save_conf.setObjectName(_fromUtf8("button_save_conf"))
        self.tab_widget_conf = QtGui.QTabWidget(self.tab_2)
        self.tab_widget_conf.setGeometry(QtCore.QRect(490, 10, 511, 411))
        self.tab_widget_conf.setObjectName(_fromUtf8("tab_widget_conf"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.combo_box_changew = QtGui.QComboBox(self.tab)
        self.combo_box_changew.setGeometry(QtCore.QRect(200, 220, 261, 22))
        self.combo_box_changew.setObjectName(_fromUtf8("combo_box_changew"))
        self.combo_box_changew.addItem(_fromUtf8(""))
        self.combo_box_changew.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(70, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.combo_box_minimizew = QtGui.QComboBox(self.tab)
        self.combo_box_minimizew.setGeometry(QtCore.QRect(200, 140, 261, 22))
        self.combo_box_minimizew.setObjectName(_fromUtf8("combo_box_minimizew"))
        self.combo_box_minimizew.addItem(_fromUtf8(""))
        self.combo_box_minimizew.addItem(_fromUtf8(""))
        self.combo_box_mm = QtGui.QComboBox(self.tab)
        self.combo_box_mm.setGeometry(QtCore.QRect(200, 20, 261, 22))
        self.combo_box_mm.setObjectName(_fromUtf8("combo_box_mm"))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.combo_box_click = QtGui.QComboBox(self.tab)
        self.combo_box_click.setGeometry(QtCore.QRect(200, 60, 261, 22))
        self.combo_box_click.setObjectName(_fromUtf8("combo_box_click"))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(47, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.combo_box_closew = QtGui.QComboBox(self.tab)
        self.combo_box_closew.setGeometry(QtCore.QRect(200, 180, 261, 22))
        self.combo_box_closew.setObjectName(_fromUtf8("combo_box_closew"))
        self.combo_box_closew.addItem(_fromUtf8(""))
        self.combo_box_closew.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(140, 60, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(55, 220, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(116, 260, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.combo_box_vscroll = QtGui.QComboBox(self.tab)
        self.combo_box_vscroll.setGeometry(QtCore.QRect(200, 260, 261, 22))
        self.combo_box_vscroll.setObjectName(_fromUtf8("combo_box_vscroll"))
        self.combo_box_vscroll.addItem(_fromUtf8(""))
        self.combo_box_vscroll.addItem(_fromUtf8(""))
        self.combo_box_vscroll.addItem(_fromUtf8(""))
        self.combo_box_vscroll.addItem(_fromUtf8(""))
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(116, 300, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.combo_box_hscroll = QtGui.QComboBox(self.tab)
        self.combo_box_hscroll.setGeometry(QtCore.QRect(200, 300, 261, 22))
        self.combo_box_hscroll.setObjectName(_fromUtf8("combo_box_hscroll"))
        self.combo_box_hscroll.addItem(_fromUtf8(""))
        self.combo_box_hscroll.addItem(_fromUtf8(""))
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(100, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.combo_box_rclick = QtGui.QComboBox(self.tab)
        self.combo_box_rclick.setGeometry(QtCore.QRect(200, 100, 261, 22))
        self.combo_box_rclick.setObjectName(_fromUtf8("combo_box_rclick"))
        self.combo_box_rclick.addItem(_fromUtf8(""))
        self.combo_box_rclick.addItem(_fromUtf8(""))
        self.combo_box_rclick.addItem(_fromUtf8(""))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(130, 340, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.combo_box_grabb = QtGui.QComboBox(self.tab)
        self.combo_box_grabb.setGeometry(QtCore.QRect(200, 340, 261, 22))
        self.combo_box_grabb.setObjectName(_fromUtf8("combo_box_grabb"))
        self.combo_box_grabb.addItem(_fromUtf8(""))
        self.combo_box_grabb.addItem(_fromUtf8(""))
        self.button_help_click = QtGui.QPushButton(self.tab)
        self.button_help_click.setGeometry(QtCore.QRect(470, 60, 21, 23))
        self.button_help_click.setText(_fromUtf8(""))
        self.button_help_click.setObjectName(_fromUtf8("button_help_click"))
        self.button_help_rclick = QtGui.QPushButton(self.tab)
        self.button_help_rclick.setGeometry(QtCore.QRect(470, 100, 21, 23))
        self.button_help_rclick.setText(_fromUtf8(""))
        self.button_help_rclick.setObjectName(_fromUtf8("button_help_rclick"))
        self.button_help_grabb = QtGui.QPushButton(self.tab)
        self.button_help_grabb.setGeometry(QtCore.QRect(470, 340, 21, 23))
        self.button_help_grabb.setText(_fromUtf8(""))
        self.button_help_grabb.setObjectName(_fromUtf8("button_help_grabb"))
        self.button_help_vscroll = QtGui.QPushButton(self.tab)
        self.button_help_vscroll.setGeometry(QtCore.QRect(470, 260, 21, 23))
        self.button_help_vscroll.setText(_fromUtf8(""))
        self.button_help_vscroll.setObjectName(_fromUtf8("button_help_vscroll"))
        self.tab_widget_conf.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_10 = QtGui.QLabel(self.tab_6)
        self.label_10.setGeometry(QtCore.QRect(70, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.combo_box_showdesktop = QtGui.QComboBox(self.tab_6)
        self.combo_box_showdesktop.setGeometry(QtCore.QRect(200, 20, 191, 22))
        self.combo_box_showdesktop.setObjectName(_fromUtf8("combo_box_showdesktop"))
        self.combo_box_showdesktop.addItem(_fromUtf8(""))
        self.combo_box_showdesktop.addItem(_fromUtf8(""))
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(40, 60, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.combo_box_openfexplorer = QtGui.QComboBox(self.tab_6)
        self.combo_box_openfexplorer.setGeometry(QtCore.QRect(200, 60, 191, 22))
        self.combo_box_openfexplorer.setObjectName(_fromUtf8("combo_box_openfexplorer"))
        self.combo_box_openfexplorer.addItem(_fromUtf8(""))
        self.combo_box_openfexplorer.addItem(_fromUtf8(""))
        self.label_26 = QtGui.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(135, 140, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_11 = QtGui.QLabel(self.tab_6)
        self.label_11.setGeometry(QtCore.QRect(135, 100, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.combo_box_openfexplorer_2 = QtGui.QComboBox(self.tab_6)
        self.combo_box_openfexplorer_2.setGeometry(QtCore.QRect(200, 140, 191, 22))
        self.combo_box_openfexplorer_2.setObjectName(_fromUtf8("combo_box_openfexplorer_2"))
        self.combo_box_openfexplorer_2.addItem(_fromUtf8(""))
        self.combo_box_openfexplorer_2.addItem(_fromUtf8(""))
        self.combo_box_showdesktop_2 = QtGui.QComboBox(self.tab_6)
        self.combo_box_showdesktop_2.setGeometry(QtCore.QRect(200, 100, 191, 22))
        self.combo_box_showdesktop_2.setObjectName(_fromUtf8("combo_box_showdesktop_2"))
        self.combo_box_showdesktop_2.addItem(_fromUtf8(""))
        self.combo_box_showdesktop_2.addItem(_fromUtf8(""))
        self.label_27 = QtGui.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(145, 180, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.combo_box_openfexplorer_3 = QtGui.QComboBox(self.tab_6)
        self.combo_box_openfexplorer_3.setGeometry(QtCore.QRect(200, 180, 191, 22))
        self.combo_box_openfexplorer_3.setObjectName(_fromUtf8("combo_box_openfexplorer_3"))
        self.combo_box_openfexplorer_3.addItem(_fromUtf8(""))
        self.combo_box_openfexplorer_3.addItem(_fromUtf8(""))
        self.tab_widget_conf.addTab(self.tab_6, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.combo_box_opencalc = QtGui.QComboBox(self.tab_3)
        self.combo_box_opencalc.setGeometry(QtCore.QRect(170, 20, 121, 22))
        self.combo_box_opencalc.setObjectName(_fromUtf8("combo_box_opencalc"))
        self.combo_box_opencalc.addItem(_fromUtf8(""))
        self.combo_box_opencalc.addItem(_fromUtf8(""))
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(30, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(30, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.combo_box_opentexted = QtGui.QComboBox(self.tab_3)
        self.combo_box_opentexted.setGeometry(QtCore.QRect(170, 60, 121, 22))
        self.combo_box_opentexted.setObjectName(_fromUtf8("combo_box_opentexted"))
        self.combo_box_opentexted.addItem(_fromUtf8(""))
        self.combo_box_opentexted.addItem(_fromUtf8(""))
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(30, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.combo_box_openterminal = QtGui.QComboBox(self.tab_3)
        self.combo_box_openterminal.setGeometry(QtCore.QRect(170, 100, 121, 22))
        self.combo_box_openterminal.setObjectName(_fromUtf8("combo_box_openterminal"))
        self.combo_box_openterminal.addItem(_fromUtf8(""))
        self.combo_box_openterminal.addItem(_fromUtf8(""))
        self.tab_widget_conf.addTab(self.tab_3, _fromUtf8(""))
        self.tab_widget_frames = QtGui.QTabWidget(self.tab_2)
        self.tab_widget_frames.setGeometry(QtCore.QRect(35, 10, 411, 411))
        self.tab_widget_frames.setObjectName(_fromUtf8("tab_widget_frames"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_frame_XY = QtGui.QLabel(self.tab_4)
        self.label_frame_XY.setGeometry(QtCore.QRect(0, 0, 411, 401))
        self.label_frame_XY.setObjectName(_fromUtf8("label_frame_XY"))
        self.tab_widget_frames.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_frame_XZ = QtGui.QLabel(self.tab_5)
        self.label_frame_XZ.setGeometry(QtCore.QRect(0, 0, 411, 401))
        self.label_frame_XZ.setObjectName(_fromUtf8("label_frame_XZ"))
        self.tab_widget_frames.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.label_gesture_gif = QtGui.QLabel(self.tab_7)
        self.label_gesture_gif.setGeometry(QtCore.QRect(0, 0, 411, 391))
        self.label_gesture_gif.setObjectName(_fromUtf8("label_gesture_gif"))
        self.tab_widget_frames.addTab(self.tab_7, _fromUtf8(""))
        self.tab_widget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_gestures = QtGui.QWidget()
        self.tab_gestures.setObjectName(_fromUtf8("tab_gestures"))
        self.combo_box_gestures = QtGui.QComboBox(self.tab_gestures)
        self.combo_box_gestures.setGeometry(QtCore.QRect(150, 430, 161, 22))
        self.combo_box_gestures.setObjectName(_fromUtf8("combo_box_gestures"))
        self.combo_box_gestures.addItem(_fromUtf8(""))
        self.combo_box_gestures.addItem(_fromUtf8(""))
        self.combo_box_gestures.addItem(_fromUtf8(""))
        self.tab_widget.addTab(self.tab_gestures, _fromUtf8(""))
        self.tab_data = QtGui.QWidget()
        self.tab_data.setObjectName(_fromUtf8("tab_data"))
        self.text_edit = QtGui.QTextEdit(self.tab_data)
        self.text_edit.setEnabled(True)
        self.text_edit.setGeometry(QtCore.QRect(40, 50, 371, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_edit.setFont(font)
        self.text_edit.setObjectName(_fromUtf8("text_edit"))
        self.text_edit_2 = QtGui.QTextEdit(self.tab_data)
        self.text_edit_2.setEnabled(True)
        self.text_edit_2.setGeometry(QtCore.QRect(540, 50, 371, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_edit_2.setFont(font)
        self.text_edit_2.setObjectName(_fromUtf8("text_edit_2"))
        self.button_load_text = QtGui.QPushButton(self.tab_data)
        self.button_load_text.setGeometry(QtCore.QRect(40, 410, 121, 23))
        self.button_load_text.setObjectName(_fromUtf8("button_load_text"))
        self.tab_widget.addTab(self.tab_data, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(46, 520, 71, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_leap_status = QtGui.QLabel(self.centralwidget)
        self.label_leap_status.setGeometry(QtCore.QRect(120, 520, 111, 21))
        self.label_leap_status.setText(_fromUtf8(""))
        self.label_leap_status.setObjectName(_fromUtf8("label_leap_status"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(220, 510, 3, 61))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(240, 517, 82, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(340, 517, 82, 20))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(433, 510, 3, 61))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(820, 520, 111, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menubar_file = QtGui.QMenu(self.menubar)
        self.menubar_file.setObjectName(_fromUtf8("menubar_file"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar_file_loadconf = QtGui.QAction(MainWindow)
        self.menubar_file_loadconf.setObjectName(_fromUtf8("menubar_file_loadconf"))
        self.menubar_file_newconfiguration = QtGui.QAction(MainWindow)
        self.menubar_file_newconfiguration.setObjectName(_fromUtf8("menubar_file_newconfiguration"))
        self.menubar_file_saveconf = QtGui.QAction(MainWindow)
        self.menubar_file_saveconf.setObjectName(_fromUtf8("menubar_file_saveconf"))
        self.actionTutorial = QtGui.QAction(MainWindow)
        self.actionTutorial.setObjectName(_fromUtf8("actionTutorial"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menubar_file.addAction(self.menubar_file_loadconf)
        self.menubar_file.addAction(self.menubar_file_saveconf)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menubar_file.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(1)
        self.tab_widget_conf.setCurrentIndex(0)
        self.combo_box_mm.setCurrentIndex(1)
        self.tab_widget_frames.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CANVAS", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Left click to recognize. q for quit. c for clear.</p><p align=\"center\">Templates: T, V, right, left</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "canvas size (900, 400)", None))
        self.combo_box.setItemText(0, _translate("MainWindow", "1 Finger", None))
        self.combo_box.setItemText(1, _translate("MainWindow", "All Fingers", None))
        self.label_3.setText(_translate("MainWindow", "Record: ", None))
        self.radioButton_NN.setText(_translate("MainWindow", "NN", None))
        self.radioButton_pd.setText(_translate("MainWindow", "P$", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_canvas), _translate("MainWindow", "Canvas", None))
        self.button_restore_def.setText(_translate("MainWindow", "Restore Defaults", None))
        self.button_save_conf.setText(_translate("MainWindow", "Save Configuration", None))
        self.combo_box_changew.setItemText(0, _translate("MainWindow", "90 degree hand + left/right Swipe", None))
        self.combo_box_changew.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_7.setText(_translate("MainWindow", "Close Window", None))
        self.combo_box_minimizew.setItemText(0, _translate("MainWindow", "V gesture (default)", None))
        self.combo_box_minimizew.setItemText(1, _translate("MainWindow", "T gesture", None))
        self.combo_box_mm.setItemText(0, _translate("MainWindow", "finger 0", None))
        self.combo_box_mm.setItemText(1, _translate("MainWindow", "finger 1 (default / recommended)", None))
        self.combo_box_mm.setItemText(2, _translate("MainWindow", "finger 2", None))
        self.combo_box_mm.setItemText(3, _translate("MainWindow", "finger 3", None))
        self.combo_box_mm.setItemText(4, _translate("MainWindow", "finger 4", None))
        self.combo_box_click.setItemText(0, _translate("MainWindow", "CLICK plane mode (finger 1/thumb to finger 2/index) !!", None))
        self.combo_box_click.setItemText(1, _translate("MainWindow", "CLICK deep mode (finger 1/index at front)", None))
        self.combo_box_click.setItemText(2, _translate("MainWindow", "CLICK (finger 3/middle down) !!", None))
        self.combo_box_click.setItemText(3, _translate("MainWindow", "CLICK (finger 2/index down)", None))
        self.combo_box_click.setItemText(4, _translate("MainWindow", "CLICK (finger 1/thumb down)", None))
        self.label_6.setText(_translate("MainWindow", "Minimize Window", None))
        self.combo_box_closew.setItemText(0, _translate("MainWindow", "T gesture (default)", None))
        self.combo_box_closew.setItemText(1, _translate("MainWindow", "V gesture", None))
        self.label_4.setText(_translate("MainWindow", "Click", None))
        self.label_9.setText(_translate("MainWindow", "Switch Window", None))
        self.label_5.setText(_translate("MainWindow", "Mouse movement finger", None))
        self.label_18.setText(_translate("MainWindow", "V Scroll", None))
        self.combo_box_vscroll.setItemText(0, _translate("MainWindow", "5 fingers extended + up/down wrist", None))
        self.combo_box_vscroll.setItemText(1, _translate("MainWindow", "5 fingers extended + left/right wrist", None))
        self.combo_box_vscroll.setItemText(2, _translate("MainWindow", "4 fingers extended + up/down wrist", None))
        self.combo_box_vscroll.setItemText(3, _translate("MainWindow", "3 fingers extended + up/down wrist", None))
        self.label_19.setText(_translate("MainWindow", "H Scroll", None))
        self.combo_box_hscroll.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_hscroll.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_23.setText(_translate("MainWindow", "Right Click", None))
        self.combo_box_rclick.setItemText(0, _translate("MainWindow", "RCLICK plane mode (finger 3/middle down) !!", None))
        self.combo_box_rclick.setItemText(1, _translate("MainWindow", "RCLICK deep mode (finger 1 and 2 to front)", None))
        self.combo_box_rclick.setItemText(2, _translate("MainWindow", "RCLICK (finger 1/index down)", None))
        self.label_24.setText(_translate("MainWindow", "Grabb", None))
        self.combo_box_grabb.setItemText(0, _translate("MainWindow", "f2 and f3 together", None))
        self.combo_box_grabb.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.tab_widget_conf.setTabText(self.tab_widget_conf.indexOf(self.tab), _translate("MainWindow", "Basic", None))
        self.label_10.setText(_translate("MainWindow", "Show Desktop", None))
        self.combo_box_showdesktop.setItemText(0, _translate("MainWindow", "CLICK plane mode (finger 0 to finger 1)", None))
        self.combo_box_showdesktop.setItemText(1, _translate("MainWindow", "CLICK deep mode (finger 1 at front)", None))
        self.label_25.setText(_translate("MainWindow", "Open File Explorer", None))
        self.combo_box_openfexplorer.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_openfexplorer.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_26.setText(_translate("MainWindow", "Paste", None))
        self.label_11.setText(_translate("MainWindow", "Copy", None))
        self.combo_box_openfexplorer_2.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_openfexplorer_2.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.combo_box_showdesktop_2.setItemText(0, _translate("MainWindow", "CLICK plane mode (finger 0 to finger 1)", None))
        self.combo_box_showdesktop_2.setItemText(1, _translate("MainWindow", "CLICK deep mode (finger 1 at front)", None))
        self.label_27.setText(_translate("MainWindow", "Cut", None))
        self.combo_box_openfexplorer_3.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_openfexplorer_3.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.tab_widget_conf.setTabText(self.tab_widget_conf.indexOf(self.tab_6), _translate("MainWindow", "Extra", None))
        self.combo_box_opencalc.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_opencalc.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_20.setText(_translate("MainWindow", "Open Calculator", None))
        self.label_21.setText(_translate("MainWindow", "Open Text Editor", None))
        self.combo_box_opentexted.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_opentexted.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_22.setText(_translate("MainWindow", "Open CMD", None))
        self.combo_box_openterminal.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_openterminal.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.tab_widget_conf.setTabText(self.tab_widget_conf.indexOf(self.tab_3), _translate("MainWindow", "Applications", None))
        self.label_frame_XY.setText(_translate("MainWindow", "TextLabel", None))
        self.tab_widget_frames.setTabText(self.tab_widget_frames.indexOf(self.tab_4), _translate("MainWindow", "XY", None))
        self.label_frame_XZ.setText(_translate("MainWindow", "TextLabel", None))
        self.tab_widget_frames.setTabText(self.tab_widget_frames.indexOf(self.tab_5), _translate("MainWindow", "XZ", None))
        self.label_gesture_gif.setText(_translate("MainWindow", "TextLabel", None))
        self.tab_widget_frames.setTabText(self.tab_widget_frames.indexOf(self.tab_7), _translate("MainWindow", "Gesture", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Configuration", None))
        self.combo_box_gestures.setItemText(0, _translate("MainWindow", "CLICK plane mode", None))
        self.combo_box_gestures.setItemText(1, _translate("MainWindow", "GRABB plane mode", None))
        self.combo_box_gestures.setItemText(2, _translate("MainWindow", "SCROLL", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_gestures), _translate("MainWindow", "Gestures", None))
        self.button_load_text.setText(_translate("MainWindow", "load Text", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_data), _translate("MainWindow", "Data", None))
        self.label_8.setText(_translate("MainWindow", "LEAP Status", None))
        self.radioButton.setText(_translate("MainWindow", "Plane Mode", None))
        self.radioButton_2.setText(_translate("MainWindow", "Deep Mode", None))
        self.checkBox.setText(_translate("MainWindow", "Launch on startup", None))
        self.menubar_file.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menubar_file_loadconf.setText(_translate("MainWindow", "Load Configuration", None))
        self.menubar_file_newconfiguration.setText(_translate("MainWindow", "New Configuration", None))
        self.menubar_file_saveconf.setText(_translate("MainWindow", "Save Configuration", None))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))

